//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public short ID_CIUDAD { get; set; }
        public string NOMBRE { get; set; }
        public short REGION_ID_REGION { get; set; }
    
        public virtual REGION REGION { get; set; }
    }
}
