//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguro.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguroEntities : DbContext
    {
        public SeguroEntities()
            : base("name=SeguroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COBERTURA> COBERTURA { get; set; }
        public DbSet<LIQUIDADOR> LIQUIDADOR { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<MODELO> MODELO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SINIESTRO> SINIESTRO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
    }
}
