//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string ID_VEHICULO { get; set; }
        public string PATENTE { get; set; }
        public short ANO { get; set; }
        public int VALOR_FISCAL { get; set; }
        public string ID_MODELO { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
